# Generated by Django 5.2.15 on 2026-07-05 16:06

import patogh_backend.idgen
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.CharField(default=patogh_backend.idgen.generate_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('text', models.TextField(verbose_name='متن درخواست')),
                ('status', models.CharField(choices=[('در حال بررسی', 'در حال بررسی'), ('بررسی شد', 'بررسی شد'), ('رد شد', 'رد شد')], default='در حال بررسی', max_length=30, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
