# Generated by Django 5.2.15 on 2026-07-05 16:06

import django.db.models.deletion
import patogh_backend.idgen
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(default=patogh_backend.idgen.generate_order_no, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200, verbose_name='نام گیرنده')),
                ('phone', models.CharField(max_length=20, verbose_name='شماره موبایل')),
                ('postal_code', models.CharField(max_length=15, verbose_name='کد پستی')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین\u200cپال')], default='zarinpal', max_length=40, verbose_name='درگاه پرداخت')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='مبلغ کل (تومان)')),
                ('status', models.CharField(choices=[('در حال بررسی', 'در حال بررسی'), ('در حال ارسال', 'در حال ارسال'), ('تحویل داده شد', 'تحویل داده شد'), ('لغو شد', 'لغو شد')], default='در حال بررسی', max_length=30, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('price', models.PositiveIntegerField()),
                ('emoji', models.CharField(blank=True, default='📚', max_length=10)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
        ),
    ]
