# Generated by Django 5.2.16 on 2026-07-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_gateway'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewaySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_id', models.CharField(blank=True, help_text='کد ترمینال/پذیرندگی\u200cای که بانک سامان یا شرکت سپ هنگام ثبت\u200cنام درگاه به شما داده است.', max_length=40, verbose_name='شناسه پذیرنده (Terminal ID)')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ذخیره')),
            ],
            options={
                'verbose_name': 'تنظیمات درگاه پرداخت',
                'verbose_name_plural': 'تنظیمات درگاه پرداخت',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('failed', 'ناموفق/لغوشده')], default='pending', max_length=10, verbose_name='وضعیت پرداخت'),
        ),
        migrations.AddField(
            model_name='order',
            name='ref_num',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='شماره پیگیری تراکنش (RefNum)'),
        ),
        migrations.AddField(
            model_name='order',
            name='sep_token',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='توکن درگاه سامان'),
        ),
        migrations.AddField(
            model_name='order',
            name='trace_no',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='شماره ترِیس بانکی (TraceNo)'),
        ),
    ]
