# Generated by Django 5.2.15 on 2026-07-05 16:06

import django.db.models.deletion
import patogh_backend.idgen
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.CharField(default=patogh_backend.idgen.generate_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام نویسنده')),
                ('bio', models.TextField(blank=True, default='', verbose_name='بیوگرافی')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': 'نویسندگان',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(default=patogh_backend.idgen.generate_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='قیمت (تومان)')),
                ('discount', models.PositiveSmallIntegerField(default=0, verbose_name='تخفیف (٪)')),
                ('category', models.CharField(default='عمومی', max_length=120, verbose_name='دسته\u200cبندی')),
                ('category2', models.BooleanField(default=False, verbose_name='کتاب دسته ۲')),
                ('emoji', models.CharField(blank=True, default='📚', max_length=10, verbose_name='ایموجی جلد')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='تصاویر')),
                ('featured', models.BooleanField(default=False, verbose_name='پیشنهاد ویژه')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='catalog.author', verbose_name='نویسنده')),
            ],
            options={
                'verbose_name': 'کتاب',
                'verbose_name_plural': 'کتاب\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
