# Generated by Django 5.2.15 on 2026-07-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_in_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='in_stock',
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد موجود'),
        ),
    ]
