# Generated manually (mirrors Django's autogenerated migration format)

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_slug_author_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discount',
            field=models.PositiveSmallIntegerField(
                default=0, verbose_name='تخفیف (٪)',
                validators=[django.core.validators.MaxValueValidator(100)],
            ),
        ),
    ]
