# Generated manually (mirrors Django's autogenerated migration format)
# No actual database change: validators only run in Python/the admin forms,
# but Django still wants the migration state to match models.py.

from django.db import migrations, models

import media_library.validators


class Migration(migrations.Migration):

    dependencies = [
        ('media_library', '0002_pdf_podcast_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfitem',
            name='cover_image',
            field=models.FileField(
                blank=True, default='', upload_to='pdf_covers/', verbose_name='عکس جلد',
                validators=[
                    media_library.validators.IMAGE_EXTENSION_VALIDATOR,
                    media_library.validators.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name='pdfitem',
            name='file',
            field=models.FileField(
                upload_to='pdfs/', verbose_name='فایل PDF',
                validators=[
                    media_library.validators.PDF_EXTENSION_VALIDATOR,
                    media_library.validators.validate_pdf_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='cover_image',
            field=models.FileField(
                blank=True, default='', upload_to='podcast_covers/', verbose_name='عکس جلد',
                validators=[
                    media_library.validators.IMAGE_EXTENSION_VALIDATOR,
                    media_library.validators.validate_image_size,
                ],
            ),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='audio_file',
            field=models.FileField(
                upload_to='podcasts/', verbose_name='فایل صوتی',
                validators=[
                    media_library.validators.AUDIO_EXTENSION_VALIDATOR,
                    media_library.validators.validate_audio_size,
                ],
            ),
        ),
    ]
