# Generated manually (mirrors Django's autogenerated migration format)

import patogh_backend.idgen
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.CharField(default=patogh_backend.idgen.generate_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('page', models.CharField(choices=[('home', 'صفحه اصلی'), ('shop', 'فروشگاه'), ('authors', 'نویسندگان'), ('contact', 'تماس با ما'), ('checkout', 'ثبت نهایی پرداخت')], max_length=20, verbose_name='صفحه')),
                ('position', models.CharField(choices=[('left', 'چپ'), ('right', 'راست')], max_length=10, verbose_name='موقعیت')),
                ('media_type', models.CharField(choices=[('image', 'عکس'), ('video', 'فیلم بی\u200cصدا')], default='image', max_length=10, verbose_name='نوع رسانه')),
                ('media', models.TextField(blank=True, default='', verbose_name='فایل (تصویر یا ویدیو)')),
                ('link_url', models.URLField(blank=True, default='', verbose_name='لینک مقصد (اختیاری)')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تبلیغ',
                'verbose_name_plural': 'تبلیغات',
                'ordering': ['page', 'position'],
                'unique_together': {('page', 'position')},
            },
        ),
    ]
