# Generated manually (mirrors Django's autogenerated migration format)

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(
                choices=[('left', 'باکس ۱'), ('right', 'باکس ۲')],
                max_length=10, verbose_name='باکس',
            ),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='pos_x',
            field=models.FloatField(
                blank=True, null=True, verbose_name='فاصله از چپ (٪ عرض صفحه)',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='pos_y',
            field=models.FloatField(
                default=42.0, verbose_name='فاصله از بالا (٪ ارتفاع صفحه)',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='width',
            field=models.PositiveIntegerField(
                default=150, verbose_name='عرض (پیکسل)',
                validators=[
                    django.core.validators.MinValueValidator(60),
                    django.core.validators.MaxValueValidator(500),
                ],
            ),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='height',
            field=models.PositiveIntegerField(
                default=300, verbose_name='ارتفاع (پیکسل)',
                validators=[
                    django.core.validators.MinValueValidator(60),
                    django.core.validators.MaxValueValidator(900),
                ],
            ),
        ),
    ]
