# Generated manually (mirrors Django's autogenerated migration format)

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertising', '0002_ad_position_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advertisement',
            unique_together=set(),
        ),
        migrations.AlterModelOptions(
            name='advertisement',
            options={'ordering': ['page', '-created_at'], 'verbose_name': 'تبلیغ', 'verbose_name_plural': 'تبلیغات'},
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(
                blank=True, default='custom', max_length=20, verbose_name='موقعیت (میان‌بر)',
                choices=[
                    ('top-left', 'بالا - چپ'),
                    ('top-right', 'بالا - راست'),
                    ('middle-left', 'وسط - چپ'),
                    ('middle-right', 'وسط - راست'),
                    ('bottom-left', 'پایین - چپ'),
                    ('bottom-right', 'پایین - راست'),
                    ('custom', 'دلخواه (جابه‌جا شده با دست)'),
                ],
            ),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='pos_y',
            field=models.FloatField(
                blank=True, null=True, verbose_name='فاصله از بالا (٪ ارتفاع صفحه)',
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
    ]
