# Generated by Django 5.2.15 on 2026-07-05 15:59

import patogh_backend.idgen
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(default=patogh_backend.idgen.generate_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='متن')),
                ('direction', models.CharField(choices=[('rtl', 'راست\u200cبه\u200cچپ (فارسی)'), ('ltr', 'چپ\u200cبه\u200cراست (انگلیسی)')], default='rtl', max_length=3, verbose_name='جهت نوشتار')),
                ('published', models.BooleanField(default=True, verbose_name='منتشر شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'پست وبلاگ',
                'verbose_name_plural': 'پست\u200cهای وبلاگ',
                'ordering': ['-created_at'],
            },
        ),
    ]
