# Generated by Django 5.2.15 on 2026-07-05 16:16

import django.db.models.deletion
import patogh_backend.idgen
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default=patogh_backend.idgen.generate_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='نام')),
                ('content', models.TextField(verbose_name='متن دیدگاه')),
                ('approved', models.BooleanField(default=True, verbose_name='تأیید شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post', verbose_name='مطلب')),
            ],
            options={
                'verbose_name': 'دیدگاه',
                'verbose_name_plural': 'دیدگاه\u200cها',
                'ordering': ['created_at'],
            },
        ),
    ]
